actor/urls.py
from django.urls import path
from actor.views import actors


urlpatterns = [
	path('<slug:actor_slug>', actors, name='actors'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('notice/', views.notice, name='notice'),
    path('help/', views.help, name='help'),
    path('info/', views.info, name='info'),
    path('marvel/', views.marvel, name='marvel'),
    path('korean/', views.korean, name='korean'),
    path('nolan/', views.nolan, name='nolan'),
    path('tarantino/', views.tarantino, name='tarantino'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/comments/', views.create_comment, name='create_comment'),
    path('<int:article_pk>/like/', views.like, name='like'),
]

imdb_clone/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from authy.views import UserProfile, ReviewDetail, like, unlike, UserProfileMoviesWatched, UserProfileSeriesWatched, UserProfileWatchList, UserProfileMoviesReviewed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/', include('movie.urls')),
    path('actors/', include('actor.urls')),
    path('account/', include('authy.urls')),
    path('community/', include('community.urls')),
    path('<username>/', UserProfile, name='profile'),
    path('<username>/movieswatched', UserProfileMoviesWatched, name='profile-movies-watched'),
    path('<username>/serieswatched', UserProfileSeriesWatched, name='profile-series-watched'),
    path('<username>/watchlist', UserProfileWatchList, name='profile-watch-list'),
    path('<username>/reviewed', UserProfileMoviesReviewed, name='profile-reviewed-list'),
    path('<username>/review/<imdb_id>', ReviewDetail, name='user-review'),
    path('<username>/review/<imdb_id>/like', like, name='user-review-like'),
    path('<username>/review/<imdb_id>/unlike', unlike, name='user-review-unlike'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

community/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import BooleanField
# from django.db.models import Count
from django.conf import settings
import os
from PIL import Image

CATEGORY = [('INFO', '정보게시판'), ('HELP', '요청사항'), ('MARVEL', '마블극장'), ('TARANTINO', '타란티노극장'), ('NOLAN', '놀란극장'), ('KOREAN', '한국영화극장')]

def user_directory_path(instance, filename):
	article_pic_name = f'articles/{instance.title}.jpg'
	full_path = os.path.join(settings.MEDIA_ROOT, article_pic_name)

	if os.path.exists(full_path):
		os.remove(full_path)
	return article_pic_name


class Article(models.Model):
    notice = models.BooleanField(default=False, blank=True)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cate = models.CharField(max_length=50, blank=True, choices=CATEGORY)
    views_count = models.IntegerField(default=0, blank=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    picture = models.ImageField(upload_to=user_directory_path, blank=True, null=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        SIZE = 250, 250

        if self.picture:
            pic = Image.open(self.picture.path)
            pic.thumbnail(SIZE, Image.LANCZOS)
            pic.save(self.picture.path)

    # hate_users = models.ManyToManyField(User, related_name='hate_articles', blank=True)
    # image_link = models.TextField(default = '', blank=True)
    # youtube_link = models.TextField(default='', blank=True)
    

class ArticleComment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

community/forms.py
from django import forms
from .models import Article, CATEGORY, ArticleComment


class ArticleForm(forms.ModelForm):
    cate = forms.ChoiceField(choices=CATEGORY, widget=forms.Select(), required=True)
    picture = forms.ImageField(required=False)
    
    class Meta:
        model = Article
        fields = ['cate', 'title', 'content', 'picture']


class ArticleCommentForm(forms.ModelForm):

    class Meta:
        model = ArticleComment
        exclude = ['article', 'user']

community/views.py
from django.db.models.expressions import OrderBy
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from .models import Article, ArticleComment
from .forms import ArticleForm, ArticleCommentForm
from django.db.models import Count

@require_GET
def help(request):
    articles = Article.objects.filter(cate='HELP').order_by('-like_users')
    context = {
        'articles': articles,
    }
    return render(request, 'community/help.html', context)

@require_GET
def notice(request):
    articles = Article.objects.filter(notice=True)
    context = {
        'articles': articles,
    }
    return render(request, 'community/notice.html', context)

@require_GET
def info(request):
    # info_articles = Article.objects.filter(cate='INFO')
    # for info_article in info_articles:
    #     if info_article.like_users.count() >= 20 :
    #         info_article.notice = True
    # info_articles.save()
    articles = Article.objects.filter(cate='INFO').order_by('-like_users')
    context = {
        'articles': articles,
    }
    return render(request, 'community/info.html', context)

@require_GET
def marvel(request):
    articles = Article.objects.filter(cate='MARVEL').order_by('-like_users')
    context = {
        'articles': articles,
    }
    return render(request, 'community/marvel.html', context)

@require_GET
def tarantino(request):
    articles = Article.objects.filter(cate='TARANTINO').order_by('-like_users')
    context = {
        'articles': articles,
    }
    return render(request, 'community/tarantino.html', context)

@require_GET
def ticket_box(request):
    articles = Article.objects.filter(cate='TICKET_BOX').order_by('-like_users')
    context = {
        'articles': articles,
    }
    return render(request, 'community/ticket_box.html', context)
    
@require_GET
def korean(request):
    articles = Article.objects.filter(cate='KOREAN').order_by('-like_users')
    context = {
        'articles': articles,
    }
    return render(request, 'community/korean.html', context)

@require_GET
def nolan(request):
    articles = Article.objects.filter(cate='NOLAN').order_by('-like_users')
    context = {
        'articles': articles,
    }
    return render(request, 'community/nolan.html', context)

@require_GET
def index(request):
    articles = Article.objects.all().annotate(user_count=Count('like_users')).order_by('user_count')
    context = {
        'articles': articles,
    }
    return render(request, 'community/index.html', context)


@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST) 
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('community:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'community/create.html', context)


@require_GET
def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.articlecomment_set.all()
    comment_form = ArticleCommentForm()
    article.views_count += 1
    article.save()
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'community/detail.html', context)


@require_POST
def create_comment(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comment_form = ArticleCommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
        return redirect('community:detail', article.pk)
    context = {
        'comment_form': comment_form,
        'article': article,
        'comments': article.comment_set.all(),
    }
    return render(request, 'community/detail.html', context)


@require_POST
def like(request, article_pk, mode=0):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        user = request.user

        if mode and article.like_users.filter(pk=user.pk).exists():
            article.like_users.remove(user)
            liked = False
        else:
            if article.like_users.filter(pk=user.pk).exists():
                article.like_users.remove(user)
                liked = False
            else:   
                article.like_users.add(user)
                liked = True
                # hate(request, article_pk, 1)
        
        like_status = {
            'liked' : liked,
            'count' : article.like_users.count(),
        }
        return JsonResponse(like_status)
    return HttpResponse(status=401)

imdb_clone/templates/community/create.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">글쓰기</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
  <hr>
    <button class="btn black white-text right" type="submit"><b>제출하기</b></button>
  </form>
  <button class="btn black white-text left" onclick = "location.href = '{% url 'community:index' %}'"><b>뒤로가기</b></button>
{% endblock %}

imdb_clone/templates/community/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  {% if article.cate == 'MARVEL' %}
    <h3>마블 극장</h3>
  {% elif article.cate == 'HELP'%}
    <h3>문의 및 요청사항<h3>
  {% elif article.cate == 'INFO'%}
    <h3>정보 공유 게시판<h3>
  {% elif article.cate == 'NOTICE'%}
    <h3>공지사항<h3>
  {% elif article.cate == 'TARANTINO'%}
    <h3>타란티노 극장<h3>
  {% elif article.cate == 'KOREAN'%}
    <h3>한국영화 극장<h3>
  {% elif article.cate == 'NOLAN'%}
    <h3>놀란 극장<h3>
  {% endif %}
  <hr>
  <h5>{{ article.title }}</h5>
  <br>
  <div style="display:flex; justify-content:space-between; ">
    <p>작성자: {{ article.user }}</p>
    <p>조회수: {{ article.views_count }}</p>
  </div>
  <hr style="margin-top:0px;">
  {% if article.picture %}
    <img src="{{ article.picture.url }}">
  {% endif %}
  <div style="font-size:16px;">{{ article.content }}</div>
  <br>
  <hr>
  <p>작성 시각: {{ article.created_at }}</p>
  <p>수정 시각: {{ article.updated_at }}</p>
  {% comment %} <p>{{ article.youtube_link }}</p> {% endcomment %}
  {% comment %} <div>
    <iframe src="{{ article.youtube_link }}" frameborder="0"></iframe>
  </div>
  <div id='youtube' style="position: relative; height:0; padding-bottom: 56.25%;">
    <iframe width="560" height="315" src="{{ article.youtube_link }}" art="동영상을 찾을수 없습니다." frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen style="position: absolute; width:100%; height:100%;"></iframe>
  </div> {% endcomment %}





  <form class="like-form d-inline" data-id="{{ article.pk }}">
      {% csrf_token %}

      {% if user in article.like_users.all %}
        <button class="btn btn-link">
          <i id="like-{{ article.pk }}" class="fas fa-heart fa-lg" style="color:crimson;"></i>
        </button>
      {% else %}
        <button class="btn btn-link red left">
          <i id="like-{{ article.pk }}"class="material-icons">favorite_border</i>
        </button>
      {% endif %}
    </form>
    <span class="right" id="count-{{ article.pk }}">추천수: {{ article.like_users.all|length }}</span><br>

  
  
  <br>
  <hr>
  <h4>댓글 목록</h4>
  <br>
  {% if comments|length %}
    <p><b>{{ comments|length }}개의 댓글이 있습니다.</b></p><br>
  {% endif %}
  {% for comment in comments %}
    <div>
      {{ comment.user }} - {{ comment.content }}
    </div>
    <br>
  {% empty %}
    <p><b>댓글이 없어요..</b></p>
  {% endfor %}
  <hr>
  {% if request.user.is_authenticated %}
    <form action="{% url 'community:create_comment' article.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form }}
      <button class="btn black white-text right" type="submit"><b>제출하기</b></button>
    </form>
  {% else %}
    <button class="btn black white-text right tooltip" data-position="bottom" data-tooltip="로그인 해주세요" onclick = "location.href = '{% url 'login' %}'">제출하기</button>
  {% endif %}
  <button class="btn black white-text left" onclick = "location.href = '{% url 'community:index' %}'"><b>뒤로가기</b></button>

  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
  const forms = document.querySelectorAll('.like-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

  forms.forEach(function (form) {
    form.addEventListener('submit', function (event) {
      event.preventDefault()
      const articleId = event.target.dataset.id
 axios.post(`http://127.0.0.1:8000/community/${articleId}/like/`, {}, {headers: {'X-CSRFToken' : csrftoken}})
      .then(function (response) {
        const liked = response.data.liked
        const count = response.data.count

        /* const require_login = response.request.responseURL.includes('login') ? response.request.responseURL : false
        if ( require_login ) {
      window.location.href = require_login
        } */
        const likeButton = document.querySelector(`#like-${articleId}`)
        likeButton.style.color = liked ? 'crimson' : 'black'
        const likeCount = document.querySelector(`#count-${articleId}`)
        likeCount.innerText = `추천수: ${count}`
      })
      .catch((error) => {
        if (error.response.status === 401) {
          window.location.href = '../../account/login/'
        }
      })
    })
  })
  
  
    

  </script>
{% endblock  %}

imdb_clone/templates/community/help.html
{% extends 'base.html' %}

{% block content %}
  <h1>문의 & 요청사항</h1>
  <p>문의 사항및 극장 개설에 관한 요청사항을 올려주세요</p>
  <button class="btn black left"><a class="white-text" href="{% url 'community:index' %}"><b>돌아가기</b></a><br></button><br><br>
  {% if user.is_authenticated %}
    <button class="btn black right"><a class="white-text" href="{% url 'community:create' %}"><b>글쓰기</b></a></button>
  {% else %}
    <button class="btn black right"><a class="white-text" href="{% url 'login' %}"><b>로그인 해주세요</b></a></button>
  {% endif %}
  <br>
  <div>
    {% for article in articles %}
      <p><b>작성자 : <a href="{% url 'profile' article.user.username %}">{{ article.user }}</a></b></p>
      <h5><a href="{% url 'community:detail' article.pk %}">{{ article.title }}</a></h5> 
      <hr>
    {% endfor %}
  </div>
  
{% endblock %}

imdb_clone/templates/community/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
.text-container {
   height:35px;
   overflow:hidden;
   border-radius:10px;
   width:80%;
}
.text-container ul {
  color:#fff;
  background:black;
  padding-left:10px;
  padding-right:10px;
  text-align:center;
  list-style:none;
  animation: 12s linear 0s normal none infinite change1;
  -webkit-animation: 12s linear 0s normal none infinite change1;
  -moz-animation:12s linear 0s normal none infinite change1;
  -o-animation:12s linear 0s normal none infinite change1;
}

.text-container ul li {
  font-size:22px;
  line-height:35px;
  
}

@-webkit-keyframes change1 {
  0%   {margin-top:0px;}
  15%  {margin-top:0px;}
  25%  {margin-top:-35px;}
  40%  {margin-top:-35px;}
  50%  {margin-top:-70px;}
  65%  {margin-top:-70px;}
  75%  {margin-top:-35px;}
  85%  {margin-top:-35px;}
  100% {margin-top:0;}
}
@keyframes change1 {
  0%   {margin-top:0px;}
  15%  {margin-top:0px;}
  25%  {margin-top:-35px;}
  40%  {margin-top:-35px;}
  50%  {margin-top:-70px;}
  65%  {margin-top:-70px;}
  75%  {margin-top:-35px;}
  85%  {margin-top:-35px;}
  100% {margin-top:0;}
}

{% endblock %}
{% block content %}
<background-image src="..img/marvel.jpg"></background-image>
  <br>
  <h4 class="text-center mt-5 mb-5">지상 최대의 Yeong-Cha에서 영화에 관한 이야기를 공유하세요!</h4>
  <hr>
  <div class="center">
    <button style="margin-bottom: 3px"type="button" class="btn black btn-outline-dark"><a class="white-text" href="{% url 'community:notice' %}"><b>공지사항</b></a></button>
    <button style="margin-bottom: 3px"class="btn black"><a class="white-text" href="{% url 'community:help' %}"><b>문의 & 요청사항</b></a></button>
    <button style="margin-bottom: 3px"class="btn black"><a class="white-text" href="{% url 'community:info' %}"><b>정보게시판</b></a></button>
    <button style="margin-bottom: 3px"class="btn black"><a class="white-text" href="{% url 'community:marvel' %}"><b>마블 극장</b></a></button>
    <button style="margin-bottom: 3px"class="btn black"><a class="white-text" href="{% url 'community:tarantino' %}"><b>타란티노 극장</b></a></button>
    <button style="margin-bottom: 3px"class="btn black"><a class="white-text" href="{% url 'community:korean' %}"><b>한국영화 극장</b></a></button>
    <button style="margin-bottom: 3px"class="btn black"><a class="white-text" href="{% url 'community:nolan' %}"><b>놀란 극장</b></a></button>
  </div>
  <br>

  <hr>
  <div>
    <div class="text-container left" style="margin-left: 3rem">
      <ul>
        {% for article in articles %}
          <li><a class="white-text" href="{% url 'community:detail' article.pk %}">{{ article.title }}</a></li>
        {% endfor %}
      </ul>
    </div>
    {% comment %} <h4>인기글</h4> {% endcomment %}
    {% if user.is_authenticated %}
      <button class="justify-content-end btn black right" style="margin-top: 3px"><a class="white-text" onclick = "location.href = '{% url 'community:create' %}'"><b>글쓰기</b></a></button>
    {% else %}
      <button class="btn black right" style="margin-top: 3px" onclick = "location.href = '{% url 'login' %}'"><div class="tooltipped white-text" data-position="bottom" data-tooltip="로그인 해주세요"><b>글쓰기</b></div></button>
    {% endif %}
  </div>
  <table class="striped">
    <thead>
      <tr>
          <th class="center"><h5><b>제목</b></h5></th>
          <th class="center"><h5><b>극장</b></h5></th>
          <th class="center"><h5><b>작성자</b></h5></th>
      </tr>
    </thead>
    <tbody>
      {% for article in articles %}
        <tr>
          <td class="center"><a href="{% url 'community:detail' article.pk %}">{{ article.title }}</a></td>
          <td class="center">{{ article.cate }}</td>
          <td class="center">{{ article.user }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <br>
  <br>
  
{% endblock %}

{% block script %}

{% endblock %}

imdb_clone/templates/community/info.html
{% extends 'base.html' %}

{% block content %}
  <h1>정보 게시판</h1>
  <p>사이트 이용 팁 & 각종 정보 공유 공간</p>
  <button class="left btn black"><a class="white-text" href="{% url 'community:index' %}"><b>돌아가기</b></a><br></button>
  {% if user.is_authenticated %}
    <button class="btn black right"><a class="white-text" href="{% url 'community:create' %}"><b>글쓰기</b></a></button>
  {% else %}
    <button class="btn black right tooltip" data-position="bottom" data-tooltip="로그인 해주세요"><a class="white-text" href="{% url 'login' %}"><b>글쓰기</b></a></button>
  {% endif %}
  <br>
  <br>
  <br>
  <div>
    {% for article in articles %}
      <p><b>작성자 : <a href="{% url 'profile' article.user.username %}">{{ article.user }}</a></b></p>
      <h5><a href="{% url 'community:detail' article.pk %}">{{ article.title }}</a></h5> 
      <hr>
    {% endfor %}
  </div>
  
{% endblock %}

imdb_clone/templates/community/korean.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
body{
  background-image: url("{% static 'img/korea.jpg' %}");
  background-size: cover;
}

{% endblock  %}
{% block content %}

<div class="backcontainer" style="margin-top: 3rem; background-color: white; opacity: 0.8;">
  <div class="center" style="padding: 3rem">
    <img class="center" style="width: 35rem; height: 13rem;" src="{% static 'img/korea_logo.jpg'%}" alt="">
    <h4><b>신토불이 영화를 사랑하는 사람들의 모임</b></h4>
    <hr>
    <button class="btn black white-text left" onclick = "location.href = '{% url 'community:index' %}'"><b>돌아가기</b></button>
    {% if user.is_authenticated %}
      <button class="btn black white-text right" onclick = "location.href = '{% url 'community:create' %}'"><b>글쓰기</b></button>
    {% else %}
      <button class="btn black white-text right tooltip" data-position="botton" data-tooltip="로그인을 해주세요" onclick = "location.href = '{% url 'login' %}'"><b>글쓰기</b></button>
    {% endif %}
    <table class="striped">
      <thead>
        <tr>
            <th class="center"><h5><b>제목</b></h5></th>
            <th class="center"><h5><b>극장</b></h5></th>
            <th class="center"><h5><b>작성자</b></h5></th>
            <th class="center"><h5><b>내용</b></h5></th>
            <th class="center"><h5><b>추천수</b></h5></th>
        </tr>
      </thead>
      <tbody>
        {% for article in articles %}
          <tr>
            <td class="center"><a href="{% url 'community:detail' article.pk %}">{{ article.title }}</a></td>
            <td class="center">{{ article.cate }}</td>
            <td class="center">{{ article.user }}</td>
            <td class="center">{{ article.content }}</td>
            <td class="center">{{ article.like_users.all|length }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% comment %} {% for article in articles %}
      <p><b>극장 : {{ article.cate }}</b></p>
      <p><b>작성자 : <a href="{% url 'profile' article.user.username %}">{{ article.user }}</a></b></p>
      <p>글 번호: {{ article.pk }}</p>
      <p>글 제목: {{ article.title }}</p>
      <p>글 내용: {{ article.content }}</p>
      <span id="count-{{ article.pk }}"> 추천수: {{ article.like_users.all|length }} </span><br>
      <a href="{% url 'community:detail' article.pk %}">[detail]</a>
      <hr>
    {% endfor %} {% endcomment %}
    <br>
  </div>
</div>
  
{% endblock %}

imdb_clone/templates/community/marvel.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
body{
  background-image: url("{% static 'img/marvel1.png' %}");
  background-size: cover;
}

{% endblock  %}
{% block content %}

<div class="backcontainer" style="margin-top: 3rem; background-color: white; opacity: 0.8;">
  <div class="center" style="padding: 3rem">
    <img class="center" style="width: 30rem; height: 10rem;" src="{% static 'img/marvel_logo.png'%}" alt="">
    <h4><b>3000만큼 사랑하는 마블 팬들의 모임</b></h4>
    <hr>
    <button class="btn black white-text left" onclick = "location.href = '{% url 'community:index' %}'"><b>돌아가기</b></button>
    {% if user.is_authenticated %}
      <button class="btn black white-text right" onclick = "location.href = '{% url 'community:create' %}'"><b>글쓰기</b></button>
    {% else %}
      <button class="btn black white-text right tooltip" data-position="botton" data-tooltip="로그인을 해주세요" onclick = "location.href = '{% url 'login' %}'"><b>글쓰기</b></button>
    {% endif %}
    <table class="striped">
      <thead>
        <tr>
            <th class="center"><h5><b>제목</b></h5></th>
            <th class="center"><h5><b>극장</b></h5></th>
            <th class="center"><h5><b>작성자</b></h5></th>
            <th class="center"><h5><b>내용</b></h5></th>
            <th class="center"><h5><b>추천수</b></h5></th>
        </tr>
      </thead>
      <tbody>
        {% for article in articles %}
          <tr>
            <td class="center"><a href="{% url 'community:detail' article.pk %}">{{ article.title }}</a></td>
            <td class="center">{{ article.cate }}</td>
            <td class="center">{{ article.user }}</td>
            <td class="center">{{ article.content }}</td>
            <td class="center">{{ article.like_users.all|length }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% comment %} {% for article in articles %}
      <p><b>극장 : {{ article.cate }}</b></p>
      <p><b>작성자 : <a href="{% url 'profile' article.user.username %}">{{ article.user }}</a></b></p>
      <p>글 번호: {{ article.pk }}</p>
      <p>글 제목: {{ article.title }}</p>
      <p>글 내용: {{ article.content }}</p>
      <span id="count-{{ article.pk }}"> 추천수: {{ article.like_users.all|length }} </span><br>
      <a href="{% url 'community:detail' article.pk %}">[detail]</a>
      <hr>
    {% endfor %} {% endcomment %}
    <br>
  </div>
</div>
  
{% endblock %}

imdb_clone/templates/community/nolan.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
body{
  background-image: url("{% static 'img/nolan.jpeg' %}");
  background-size: cover;
}

{% endblock  %}
{% block content %}

<div class="backcontainer" style="margin-top: 3rem; background-color: white; opacity: 0.8;">
  <div class="center" style="padding: 3rem">
    <img class="center" style="width: 35rem; height: 13rem;" src="{% static 'img/nolan_logo.jpeg'%}" alt="">
    <h4><b>크리스토퍼 놀란의 놀라운 영화를 좋아하는 사람들의 공간</b></h4>
    <hr>
    <button class="btn black white-text left" onclick = "location.href = '{% url 'community:index' %}'"><b>돌아가기</b></button>
    {% if user.is_authenticated %}
      <button class="btn black white-text right" onclick = "location.href = '{% url 'community:create' %}'"><b>글쓰기</b></button>
    {% else %}
      <button class="btn black white-text right tooltip" data-position="botton" data-tooltip="로그인을 해주세요" onclick = "location.href = '{% url 'login' %}'"><b>글쓰기</b></button>
    {% endif %}
    <table class="striped">
      <thead>
        <tr>
            <th class="center"><h5><b>제목</b></h5></th>
            <th class="center"><h5><b>극장</b></h5></th>
            <th class="center"><h5><b>작성자</b></h5></th>
            <th class="center"><h5><b>내용</b></h5></th>
            <th class="center"><h5><b>추천수</b></h5></th>
        </tr>
      </thead>
      <tbody>
        {% for article in articles %}
          <tr>
            <td class="center"><a href="{% url 'community:detail' article.pk %}">{{ article.title }}</a></td>
            <td class="center">{{ article.cate }}</td>
            <td class="center">{{ article.user }}</td>
            <td class="center">{{ article.content }}</td>
            <td class="center">{{ article.like_users.all|length }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% comment %} {% for article in articles %}
      <p><b>극장 : {{ article.cate }}</b></p>
      <p><b>작성자 : <a href="{% url 'profile' article.user.username %}">{{ article.user }}</a></b></p>
      <p>글 번호: {{ article.pk }}</p>
      <p>글 제목: {{ article.title }}</p>
      <p>글 내용: {{ article.content }}</p>
      <span id="count-{{ article.pk }}"> 추천수: {{ article.like_users.all|length }} </span><br>
      <a href="{% url 'community:detail' article.pk %}">[detail]</a>
      <hr>
    {% endfor %} {% endcomment %}
    <br>
  </div>
</div>
  
{% endblock %}